name: Backport Packages (Weekly)

# Every Sunday at 02:00 UTC
on:
  schedule:
    - cron: '0 2 * * 0'
  # Enables manual triggering of the workflow
  workflow_dispatch:

jobs:
  update-packages:
    runs-on: ubuntu-latest

    # Defines the Fedora container for this job
    container:
      image: fedora:latest

    steps:
      # 1. Install pre-requisites
      - name: Install pre-requisites
        run: dnf install -y patch git git-lfs

      # 2. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          lfs: true
          # We cannot use the default GITHUB_TOKEN as it is restricted and cannot
          # trigger another workflow run, which is needed here to trigger the COPR build
          token: ${{ secrets.COMMIT_TOKEN }}

      # 2.5. Configure Git safe directory
      - name: Configure Git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      # 3. Run the update script in the container
      - name: Run update script
        run: ./update.sh

      # 4. Push changes (if any)
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Backport packages from upstream
          commit_author: Nicolas Mass√© <nicolas.masse@itix.fr>
